name: 'Next Localization demo'
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download translations
        uses: simplelocalize/download@v2.1
        with:
          apiKey: 87fFE19C5b63a784D101E554f5cd75677C890A92372D02c9
          downloadPath: ./public/locales/{lang}/common.json
          downloadFormat: single-language-json
          downloadOptions: "ESCAPE_NEW_LINES" # optional
          languageKey: en # optional, it accepts only one language key
          customerId: ikea # optional, it accepts only one customer id